### ISSUE TITLE
Move starting files from recent project

### ISSUE THREAD

**Issue by hatzipanis** [batchnz/vue-firebase-starter#1]

**Comment by max8hine** [comment]
**30 July Updates:**

- Update all form related base components by using [Vue $attrs](https://vuejs.org/v2/api/#vm-attrs) and [Vue sync modifier](https://vuejs.org/v2/guide/components-custom-events.html#sync-Modifier) for 2-way data binding design. (Was v-model pattern which made the data flow logic wasn't clear)

- Update all project forms to fit with new base components design.

**Comment by hatzipanis** [comment]
This has been merged in. Closing for now, thanks @max8hine!
